# Done to increase the memory available to gradle.
org.gradle.jvmargs             = -Xmx4G
org.gradle.parallel            = true

org.gradle.configuration-cache = false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version              = 26.2-rc-2
loader_version                 = 0.19.3
loom_version                   = 1.16-SNAPSHOT

# Fabric API
compile_only_fabric_api        = true
fabric_version                 = 0.152.0+26.2

# Recipe Viewer
compile_only_rei               = true
rei_version                    = 20.0.811
jei_version                    = 27.3.0.10
eiv_version                    = 5.2.0+1.21.10
rrv_version                    = 8.3.1+26.2-pre-5

# Sodium
sodium_version                 = mc26.1.2-0.8.12-beta.2-fabric

# Iris
iris_version                   = 1.10.9+26.1-fabric

# CC: Tweaked
cct_version                    = 1.21.11-fabric:1.116.2

# Trinkets Canary
trinkets_version               = 3.11.0-1.21.10-rc1
cca_version                    = 7.1.0-beta.1

# Mod Properties
mod_version                    = 6.0.9
mod_id                         = 1
maven_group                    = com.zurrtum
archives_base_name             = create-fly
